// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onSelectWifiItem(char * net);
void onSelectWifiPassword(const char *password);
void connectToWiFi();
void sendOTP(const char *otp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
