// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_

#include "ui.h"
#include <EEPROM.h>
#include "wifi_save.h"
#include <WiFi.h>
#include "mqtt_utils.h"

void onSelectWifiItem(char *net)
{
	WiFiSave wifiSave;
	wifiSave.saveWiFiNameCredentials(String(net));
}

void onSelectWifiPassword(const char *password)
{
	WiFiSave wifiSave;
	wifiSave.saveWiFiPasswordCredentials(String(password));
}

void connectToWiFi()
{   
	delay(1000);
    WiFiSave wifiSave;
    String wifi_name = wifiSave.getWiFiName();
    String wifi_password = wifiSave.getWiFiPassword();

    WiFi.begin(wifi_name, wifi_password);

    printf(wifi_name.c_str());

    int attempts = 0;
    while (WiFi.status() != WL_CONNECTED && attempts < 20)
    {
        delay(500);
        attempts++;
    }

    if (WiFi.status() == WL_CONNECTED)
    {
        setupMQTT();
    }
    else
    {
        printf("_ui_screen_change");
        _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen2_screen_init);
    }
}