// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_

#include "ui.h"
#include "wifi_save.h"

void ui_Screen3_screen_init()
{
WiFiSave wifiSave;
String wifi_name = wifiSave.getWiFiName();

ui_Screen3 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header2 = lv_obj_create(ui_Screen3);
lv_obj_remove_style_all(ui_Header2);
lv_obj_set_width( ui_Header2, 321);
lv_obj_set_height( ui_Header2, 33);
lv_obj_set_x( ui_Header2, -1 );
lv_obj_set_y( ui_Header2, -104 );
lv_obj_set_align( ui_Header2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Header2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Header2, lv_color_hex(0x4097E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header2, lv_color_hex(0xB278FF), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_Header2, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Label6 = lv_label_create(ui_Header2);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 42 );
lv_obj_set_y( ui_Label6, 9 );
lv_label_set_text(ui_Label6, wifi_name.c_str());
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_button_create(ui_Header2);
lv_obj_set_width( ui_Button3, 30);
lv_obj_set_height( ui_Button3, 26);
lv_obj_set_x( ui_Button3, -140 );
lv_obj_set_y( ui_Button3, 1 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -2 );
lv_obj_set_y( ui_Label7, -1 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"<");

ui_TextArea1 = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextArea1, 273);
lv_obj_set_height( ui_TextArea1, 36);
lv_obj_set_x( ui_TextArea1, -2 );
lv_obj_set_y( ui_TextArea1, -47 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Password...");

ui_Keyboard1 = lv_keyboard_create(ui_Screen3);
lv_obj_set_width( ui_Keyboard1, 300);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_x( ui_Keyboard1, 0 );
lv_obj_set_y( ui_Keyboard1, 55 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1,ui_TextArea1);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
}
