// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_

#include "ui.h"
#include <WiFi.h>

void drawWifi(int i) {
    int y = -71 + 40 * i;
    
    String network = WiFi.SSID(i);
    char* networkCopy = strdup(network.c_str()); // Tạo bản sao để tránh lỗi

    ui_Panel2 = lv_obj_create(ui_Container2);
    lv_obj_set_width( ui_Panel2, 228);
    lv_obj_set_height( ui_Panel2, 33);
    lv_obj_set_x( ui_Panel2, 5 );
    lv_obj_set_y( ui_Panel2,  y);
    lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
    lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_Label5 = lv_label_create(ui_Panel2);
    lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Label5, -3 );
    lv_obj_set_y( ui_Label5, -6 );
    lv_label_set_text(ui_Label5, networkCopy);

    lv_obj_add_event_cb(ui_Panel2, [](lv_event_t* e) {
        char* net = (char*)lv_event_get_user_data(e);
        ui_event_Panel2(e, net);
    }, LV_EVENT_ALL, networkCopy);
}

void scanWiFiNetworks() {
    int networkCount = WiFi.scanNetworks();
    
    for (int i = 0; i < networkCount; i++) {
        drawWifi(i);
    }
}

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header1 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Header1);
lv_obj_set_width( ui_Header1, 321);
lv_obj_set_height( ui_Header1, 33);
lv_obj_set_x( ui_Header1, -1 );
lv_obj_set_y( ui_Header1, -104 );
lv_obj_set_align( ui_Header1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Header1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Header1, lv_color_hex(0x4097E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header1, lv_color_hex(0xB278FF), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_Header1, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Label8 = lv_label_create(ui_Header1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 42 );
lv_obj_set_y( ui_Label8, 9 );
lv_label_set_text(ui_Label8,"Wifi Setting");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_button_create(ui_Header1);
lv_obj_set_width( ui_Button4, 30);
lv_obj_set_height( ui_Button4, 26);
lv_obj_set_x( ui_Button4, -140 );
lv_obj_set_y( ui_Button4, 1 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -2 );
lv_obj_set_y( ui_Label9, -1 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"<");

ui_Container2 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 295);
lv_obj_set_height( ui_Container2, 186);
lv_obj_set_x( ui_Container2, -1 );
lv_obj_set_y( ui_Container2, 15 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    scanWiFiNetworks();
}
